language: java

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -q -d travis_ci_test -f project_documentation/database/creation.sql
  
script: "mvn clean install -B -Dspring.profiles.active=test -Dcucumber.options=\"--tags ~@ignore\""